name: pedro
region: fra
workers:
  - name: pedro
    github:
      repo: afonsomatos/pedro
      branch: master
      deploy_on_push: true
    build_command: npm install
    run_command: npm start
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1
    envs:
      - key: TELEGRAM_BOT_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: OPENROUTER_API_KEY
        scope: RUN_TIME
        type: SECRET
